### ISSUE TITLE
pulsarctl MVP

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsarctl#2]
- [x] General
   - [x] Support resource-verb style commands
   （- [ ] Support verb-resource style commands）
   - [x] Security #9 #20 #91
   - [x] Auto-Completion #3 
   - [x] Enable CI #5 #6 #112 
   - [x] Add and check License Header #69 
   - [x] Go lint #78 
- [x] Pulsar 
   - [x] Clusters #4 #8 #11 #13 #14 #17 #18 #19 #21 #22 #23 #24 #36 
   - [x] Tenants #28
   - [x] Namespaces #57 #61 #66 #64 #67 #68 #71
   - [x] Topics . #35 #48 #51 #56 #58 #76 #75 #74 #73 
   - [x] Schemas #52
   - [x] Functions #29 #30 #31 #32 #26 #25 #15 
   - [x] Sinks #47 
   - [x] Sources #45 
   - [x] broker #87 
   - [x] broker-stats #84 
   - [x] resource-quotas #90 
   - [x] ns-isolation-policy #88 
   - [x] functions-worker #92 
- [ ] BookKeeper
   - [ ] bookies #86 
   - [ ] ledger #83 
   - [ ] auto-recovery #89 
- [x] Documentation
   - [x] How to add a new command #79 
   - [x] Command description convention #77 
   - [x] Overview of pulsarctl #108
